Feature/landing screen
apptonio/apexology pull request #4
Opened 2022-12-20 16:17 UTC by apptonio

2022-12-21 08:09 UTC, PetricMatej commented on lib/screens/home/home_screen.dart
> +class HomeScreen extends StatelessWidget {
we are using getX so replace this line with class HomeScreen extends GetView<HomeController> {

2022-12-21 08:12 UTC, PetricMatej commented on lib/screens/home/home_screen.dart
> +    //final homeController = Get.put(HomeController());
delete this line, home controller can be used like: controller.somefunction

2022-12-21 11:53 UTC, lukacevica requested changes
- Refactor folder structure so that each module has it's own widgets folder with widgets used only in that module
- Make global constants file with numbers e.g. if you have constant corner radius in whole app put it in global constants etc.

2022-12-21 11:53 UTC, lukacevica commented on lib/constants/colors.dart
> +  static const grey = Color.fromRGBO(30, 39, 46, 1.0);
Try to be consistent. Use either one or the other way for colors.

2022-12-21 11:53 UTC, lukacevica commented on lib/constants/localization.dart
>    final hr = {
Each language should be in separate file.

2022-12-21 11:53 UTC, lukacevica commented on lib/constants/localization.dart
>    final en = {
Separate the words into groups for each screen/module respectively.

2022-12-21 11:53 UTC, lukacevica commented on lib/constants/text_styles.dart
> +  );
Add new line after.

2022-12-21 11:53 UTC, lukacevica commented on lib/constants/pages.dart
>  class MyRoutes {
Extract this to separate file.

2022-12-21 11:53 UTC, lukacevica commented on lib/screens/landing/landing_controller.dart
> +        if (e.code == 'wrong-password') {
Make enum with error codes and use switch here.

2022-12-21 11:53 UTC, lukacevica commented on lib/screens/home/home_screen.dart
> +            child: const Text('Sign out')),
Text not localized.

2022-12-21 11:53 UTC, lukacevica commented on lib/screens/home/home_screen.dart
> +        Text(FirebaseAuth.instance.currentUser?.email ?? ''),
For "" make constant empty and call it in cases like this.

2022-12-21 11:53 UTC, lukacevica commented on lib/widgets/shared/texts.dart
> +class MyTexts {
Don't do it like this, rather make reusable widget with default values.

2022-12-21 11:53 UTC, lukacevica commented on lib/widgets/shared/textfields.dart
> +class MyTextfields {
Don't do it like this, rather make reusable widget with default values.

2022-12-21 11:53 UTC, lukacevica commented on lib/widgets/shared/buttons.dart
> +class MyButtons {
Don't do it like this, rather make reusable widget with default values.

2023-01-03 13:06 UTC, lukacevica approved these changes

2023-01-03 13:09 UTC, PetricMatej approved these changes

2023-01-03 13:16 UTC, merged